# Libraries ----
# atualizar: utilizar somente uma library
library(extrafont)
loadfonts()
library(sidrar)
library(data.table)
library(dplyr)
library(ggtext)
library(dplyr)
library(ggplot2)
library(janitor)
library(lemon)
library(rio)
library(lubridate)
library(readr)
library(stringr)
library(hrbrthemes)
library(scales)
library(purrr)
library(cowplot)
library(tidyr)
library(forcats)
library(gridExtra)
library(ggplotify)
library(grid)
library(patchwork)
